#!/usr/bin/python
# -*- coding: utf-8 -*-

from magyarteknoc import *

menj_előre(3)
fordulj_jobbra()
menj_előre()
fordulj_balra()
menj_előre(2)
fordulj_balra()
menj_előre(1)
fordulj_jobbra(1)
menj_előre(1)
fordulj_balra()
menj_előre(1)
fordulj_balra()
menj_előre(1)
fordulj_jobbra()
menj_előre(1)
fordulj_balra()
menj_előre(1)
fordulj_balra()
menj_előre(1)
fordulj_balra()
menj_előre(5)
fordulj_balra()
menj_előre(11)
fordulj_balra()
menj_előre(4)
fordulj_balra()
menj_előre(1)
fordulj_jobbra()
menj_előre(1)
fordulj_balra()
menj_előre(1)
fordulj_balra()
menj_előre(1)
fordulj_balra()
menj_előre(1)
fordulj_balra()
menj_előre(1)
fordulj_jobbra()
menj_előre(2)
fordulj_balra()
menj_előre(1)
fordulj_jobbra()
menj_előre(1)

